### ISSUE TITLE
첫 merge 후 발견한 문제점 및 해결 방안.

### ISSUE THREAD

**Issue by leeluna0476** [leeluna0476/minishell#3]
problem:
1. 명령어를 실행하고 나서 process가 계속 남아있음?
2. 잘못된 명령어가 들어가면 미니쉘이 실행됨.
3. exit builtin이 exit이 안 됨.
4. exit에 쓰이는 ft_putstr_fd()이 ft_printf()와 충돌. segmentation fault.
5. pipeline, 환경변수 확장에서 pointer being freed is not allocated 오류.
6. outfile redirection은 파일이 없다면 생성을 하고 있는 것 같은데도 no such file or directory 오류.
7. cat을 표준 입력으로 받을 때 개행이 ^M으로 받아짐.

solution:
1. 부모 프로세스에서 wait을 하지 않아서 발생한 것으로 밝혀짐. 적절히 wait()을 해야 함.
2. 잘못된 명령어가 들어가면 미니쉘을 실행하는 것이 아니라 execve를 하지 않는 경우 fork()로 생성된 자식 프로세스가 종료하지 않는 것으로 밝혀짐. 적절히 exit()을 해야 함.
3. (알 수 없음)
4. libft의 ft_putstr_fd()를 심플한 버전으로 바꾸고, ft_printf()를 yusekim의 것으로 교체.
5. (알 수 없음)
6. (알 수 없음)
7. 아직 하지 않은 termios 관련된 것으로 추정.

**Comment by yusekim** [comment]
1. 부모 프로세스 wait보다는 재귀를 잘못짜서 exit이 제대로 안된듯?
2. 아마도 ft_assert 적용하거나 if문 조건 반대로 적어서 제대로 처리가 안된거 같음
3. 이건 진짜 모르겠음..코드 뜯어봐야함
4. 서진님과 동일하게 생각합
5. 내 확장은 완벽할텐데..ㅠ 아니었나봄
6. 이것도 2번과 비슷한 상황일듯
7. 이건 termios관련된 문제는 아닐거 같음(mandatory할때 termios함수 거의 안썼음), 애초에 cat은  systemcall이라 termios함수와는 상관이 없고 아마 시그널 관련 문제인거 같음

**Comment by leeluna0476** [comment]
7. 갑자기 또 됨. 그리고 다시 확인해보니 안될 때 bash도 안 됐음. 이유를 모르겠음.
+++
8. cat -e < Makefile과 같이 리다이렉션이 뒤에 붙는 건 괜찮은데 < Makefile cat -e처럼 앞으로 붙으니까 안 됨.

**Comment by leeluna0476** [comment]
- [x] 명령어를 실행하고 나서 process가 계속 남아있음?
- [x] 잘못된 명령어가 들어간 경우가 처리되지 않음.
- [x] exit builtin이 exit이 안 됨.
- [x] exit에 쓰이는 ft_putstr_fd()이 ft_printf()와 충돌. segmentation fault.
- [x] 환경변수 확장에서 pointer being freed is not allocated 오류. -> 확장 문제가 아니라 utils.c의 merge_strs()에서 char**의 마지막 char *를 NULL로 하지 않아서 생긴 문제였음...
- [x] pipe 안 됨. -> 실행부가 순회하며 적절히 int pipe_fds[2]와 이전에 실행된 명령어의 fd값인 prev_fd(이전 파이프의 0번지, pipe_fds[0])를 적절히 연결했었는데, 마지막 명령어의 경우에는 stdout으로 보내줘야하는데 마지막 명령어인지를 확인하는 조건이 누락되어 있었음, 재귀로 순회하기 때문에 좀 까다로웠는데, 첫 함수 호출의 재귀 depths를 저장하고 그 값을 이용해 마지막 명령어인지의 여부를 확인하여 해결
- [x] outfile redirection은 파일이 없다면 생성을 하고 있는 것 같은데도 no such file or directory 오류. -> 에러 메세지 조건문이 반대로 되어있었다.
- [x] cat을 표준 입력으로 받을 때 개행이 ^M으로 받아짐. 갑자기 또 됨. 그리고 다시 확인해보니 안될 때 bash도 안 됐음. 이유를 모르겠음.
- [x] cat -e < Makefile과 같이 리다이렉션이 뒤에 붙는 건 괜찮은데 < Makefile cat -e처럼 앞으로 붙으니까 안 됨.
- [x] cd 안 됨. -> 명령어를 새로 실행할 때마다 info를 초기화해야 하는데 처음에 한 번밖에 안 하는 것이 문제였음. 그 부분 수정하니 해결.
- [x] 빌트인 실행 여부를 depth == 1로 확인하니까 cd && ls같은 경우에 cd가 실행이 안 됨. 아니 근데 다른 빌트인은 왜 됨;; -> depth때문에 안 됨. 근데 왜 굳이 체크하는지 모르겠음.
- [x] &&와 ||가 똑같이 동작하는 듯? -> or 실행 조건을 !exit_status 으로 수정하고 해결.
- [x] builtin에서 ||가 제대로 안 됨. -> 단일 builtin의 경우 fork()를 진행하지 않고 자체적으로 실행되는데, 가장 마지막에 실행된 자식 프로세스의 종료 상태를 가져오는 ft_wait()함수가 무조건 실행되어서 종료 상태가 제대로 리턴되지 않았음, t_info구조체의 fork_num 값이 0보다 클 때만 ft_wait()을 실행시키는 걸로 해결
- [x] 환경변수 unset하고 자식 프로세스에서 환경변수가 업데이트가 안 됨.
- [x] 환경변수에 숨겨놓은 ?(exit status) 값이 업데이트가 안 됨. -> main에서 자꾸 초기화해서;;
- [x] wildcard에 대해 quote flag 저장하기. 각각의 argument마다 모두. 예: ls "*.c" *.out
- [x] export a = b와 같은 경우 처리되지 않음. -> ft_strchar(str, '=')로 찾고 해당 ptr의 char값을 널문자('\0')로 바꾸고 환경변수 이름 체크와 노드 생성을 했었는데, 엣지 케이스가 있었다. 로직을 개선해 해결
- [x] heredoc에서 개행이 ^M으로 받아짐.
- [x] heredoc g_exit_status를 env에 포함시키는 거로 바꾸기.
- [x] 자식 프로세스를 실행할 때 시그널 처리.
- [x] heredoc을 만들 때 부모에서 sig_ign()를 하니까 ^C, ^D, ^\등이 출력되는 문제 해결. -> termios or readline
- [x] heredoc ctrl+c exit code 저장하기.
- [x] heredoc ctrl+d exit code 저장하기.
- [x] 논리 연산자 전후로 파이프라인이 있으면 실행이 제대로 안 됨.
- [x] SHLVL update - 자식 쉘 진입하고 + 1.
- [x] exit, ctrl+d로 종료할 때 가장 마지막에 실행한 프로그램의 종료 코드 받아오기. -> `return (get_exitstat(&pack));`
- [x] ctrl+d -> exit 출력하기. 터미널에 여백이 없을 때 한 칸 아래로 내려감.
- [x] readline history를 불러오면 두글자씩 터미널에 남아있음. -> --처리하려고 하니 다른 조건이랑 자꾸 충돌함. 커서 위치가 저장이 되어 있어서 한 줄을 넘어가도 다음 줄로 넘어가지 않고 겹쳐서 보임. 히스토리 불러올 때 두 글자씩 잔상이 남음. 그래서 escape sequence 없애버림.-- 킹갓현준엘 덕에 해결. rl_event_hook에 커서를 업데이트하는 함수를 등록해서 입력이 들어올 때마다 커서 위치 저장.
- [x] 원래 ctrl+c 핸들러는 rl_signal_event에 핸들링 함수를 등록해놨는데 input_handler에 escape sequence와 함께 rl_event_hook에 등록해둠.
- [x] ctrl+c exit code 저장하기.
- [x] parser에서 (가 하나도 없는 )의 오류를 제대로 찾지 못함. -> flag 조건을 flag == 0 || flag < 0으로 바꿔서 해결.
- [x] tokenizer에서 입력이 공백만 들어온 경우 (아마도)substr에서 segmentation fault가 발생. 토큰화를 시작하기 전 모든 공백을 건너뛰고 시작하는 것으로 해결..
- [x] 곳곳에 있는 leaks와 double free 잡기.
- [x] Makefile 다시 짜기.
- [x] norminette.
- [x] main 정리하기.

**Comment by leeluna0476** [comment]
* 환경변수 리스트에서 ? 을 맨 앞에 놔두면 훨씬 편할 듯

**Comment by yusekim** [comment]
환경변수 확장에서 pointer being freed is not allocated 오류. -> 확장 문제가 아니라 utils.c의 `merge_strs()`에서 `char**`의 마지막 `char *`를 `NULL`로 하지 않아서 생긴 문제였음...
pipe 안 됨. -> 실행부가 순회하며 적절히 `int pipe_fds[2]`와 이전에 실행된 명령어의 fd값인 `prev_fd`(이전 파이프의 0번지, `pipe_fds[0]`)를 적절히 연결했었는데, 마지막 명령어의 경우에는 stdout으로 보내줘야하는데 마지막 명령어인지를 확인하는 조건이 누락되어 있었음, 재귀로 순회하기 때문에 좀 까다로웠는데, 첫 함수 호출의 재귀 depths를 저장하고 그 값을 이용해 마지막 명령어인지의 여부를 확인하여 해결
`outfile redirection`은 파일이 없다면 생성을 하고 있는 것 같은데도 no such file or directory 오류. -> 에러 메세지 조건문이 반대로 되었었다.
`builtin`에서 `||`가 제대로 안 됨 -> 단일 `builtin`의 경우 `fork()`를 진행하지 않고 자체적으로 실행되는데, 가장 마지막에 실행된 자식 프로세스의 종료 상태를 가져오는 `ft_wait()`함수가 무조건 실행되어서 종료 상태가 제대로 리턴되지 않았음, `t_info`구조체의 `fork_num` 값이 0보다 클 때만 `ft_wait()`을 실행시키는 걸로 해결
 export a = b와 같은 경우 처리되지 않음 -> `ft_strchar(str, '=')`로 찾고 해당 `ptr`의 `char`값을 널문자('\0')로 바꾸고 환경변수 이름 체크와 노드 생성을 했었는데, 엣지 케이스가 있었다. 로직을 개선해 해결

**Comment by leeluna0476** [comment]
```c
int	scan_n_set_redirs(t_cmd *cmd, t_env_pack *pack)
{
	t_redir	*temp;
	int		exit_code;
	char	*exit_code_str;

	temp = cmd->all_redirs;
	exit_code = 0;
	while (temp && exit_code == 0)
	{
		if (temp->type == T_D_LESSER || temp->type == T_LESSER)
			cmd->in_redirs = temp;
		else if (temp->type == T_D_GREATER || temp->type == T_GREATER)
			cmd->out_redirs = temp;
		if (temp->type == T_D_LESSER)
			exit_code = heredoc(temp, pack);
		temp = temp->next;
	}
	temp = cmd->all_redirs;
	open_check(temp, &exit_code);
//	if (exit_code)
//	{
		exit_code_str = ft_itoa(exit_code);
		add_env_node(pack, "?", exit_code_str);
		free(exit_code_str);
//	}
	return (0);
}
```

- heredoc ctrl+c exit code 저장하기.
- heredoc ctrl+d exit code 저장하기.

`if (exit_code)`
exit_code가 0이면 업데이트가 안 된다.
ctrl+d(eof)로 heredoc을 종료했을 때 exit_code가 0이 되어야 한다.

**Comment by yusekim** [comment]
Makefile 다시짜기 -> 다시짬
파이프랑 논리연산자랑 혼용해서 실행하면 동작이 제대로 안되는 문제(예: `ls | wc && ls | wc`) -> 논리 연산자 처리 함수에서 파이프 재귀를 돌기 전에 info구조체를 초기화해야하는데, 이 부분이 누락되어있어서 `waitpid()`가 의도대로 작동하지 않았음..
추가적으로 testmain.c의 임시 wait문제 해결 -> depths 비교해서 `ft_wait()`들어가는 조건문이 의도대로 작동하지 않아 수정하였더니 잘 돌아감..

**Comment by leeluna0476** [comment]
```c
void	write_heredoc(t_redir *redir, t_env_pack *pack, int inf_fd)
{
	char	*input;
	int		q_flag;
	int		l_len;

	q_flag = heredoc_q_flag(redir->filename[0]);
	l_len = ft_strlen(redir->filename[1]);
	// << eof
	// 그냥 마지막 바이트 할당 X.
	redir->filename[1][l_len] = '\0';
	input = 0;
	while (1)
	{
		if (input)
			heredoc_expander(inf_fd, input, pack, q_flag);
//		ft_printf(HEREDOC);
	// readline으로 변경. 제어문자를 입력받지 않기 위해.
		input = readline(HEREDOC);
	// 문자열을 일부가 아닌 전체를 비교해야 해서 strncmp보다는 strcmp가 적절해보였음.
		if (!input || !ft_strcmp(input, redir->filename[1]))
			break ;
	}
//	if (!input)
//		ft_printf("\n");
//	else
		free(input);
	redir->filename[1][l_len] = 0;
}

void	heredoc_expander(int fd, char *input, t_env_pack *pack, int flag)
{
	int		i;
	int		j;
	int		exp_len;
	char	*env_name;
	t_env	*target;

	i = 0;
	while (input[i])
	{
		exp_len = 0;
		if (input[i] == '$' && flag == 0)
		{
			env_name = find_env_name(input + i);
			exp_len = ft_strlen(env_name);
			target = find_env(env_name, pack);
			free(env_name);
			j = 0;
			while (target && target->value && target->value[j])
				write(fd, target->value + j++, 1);
		}
		else
			write(fd, input + i, 1);
		i += exp_len + 1;
	}
	// 모든 입력을 개행으로 구분한다.
	write(fd, "\n", 1);
	free (input);
}

int	scan_n_set_redirs(t_cmd *cmd, t_env_pack *pack)
{
	t_redir	*temp;
	int		exit_code;
	char	*exit_code_str;

	temp = cmd->all_redirs;
	exit_code = 0;
	while (temp && exit_code == 0)
	{
		if (temp->type == T_D_LESSER || temp->type == T_LESSER)
			cmd->in_redirs = temp;
		else if (temp->type == T_D_GREATER || temp->type == T_GREATER)
			cmd->out_redirs = temp;
		if (temp->type == T_D_LESSER)
			exit_code = heredoc(temp, pack);
		temp = temp->next;
	}
	temp = cmd->all_redirs;
	open_check(temp, &exit_code);
	if (exit_code)
	{
		exit_code_str = ft_itoa(exit_code);
		add_env_node(pack, "?", exit_code_str);
		free(exit_code_str);
	}
//	여기 return값이 왜 항상 0인지 의문.
//	return (0);
	return (exit_code);
}
```
변경사항:
1. get_next_line을 readline으로 변경. readline은 제어문자를 읽지 않는 기능을 가지고 있는 것 같다.
2. ft_strncmp를 ft_strcmp로 변경. << eof 로 들어오면  eof 문자 수를 기준으로 비교했을 떄 eofff같이 뒤에 다른 글자가 존재해도 무시함. 정상적으로 비교하려면 입력받은 문자열의 길이만큼 비교해야 하는데 그럴 거면 그냥 ft_strcmp를 사용하는 게 더 맞다고 생각함.
3. get_next_line은 개행까지 문자열에 포함시키지만 readline은 그렇지 않다. 그래서 eof에 따로 개행을 찍어주는 부분을 없애고 모든 입력에 대해 개행을 찍어주는 것으로 변경했다.
4. exit_code를 반환해야 하는데 0만 반환하고 있어서 변경했다.
